### ISSUE TITLE
Error when trying to add new TV series

### ISSUE THREAD

**Issue by jessestu291** [delight-im/MovieContentFilter#22]
I'm receiving this error when trying to add a new TV series:

java%0d%0ascript%0d%0a:alert(0)

**Comment by jessestu291** [comment]
It seems I now get a "try again later" message when adding a series.

**Comment by ocram** [comment]
Thanks for your feedback and appreciation!

When you’re adding a new TV series, i.e. when you’re on the page before you see the error, are you on the following page then?

https://www.moviecontentfilter.com/add?primary-type=series

If so, could you please give the exact input for all fields that leads to that error?

 * Level
 * Title
 * Year
 * IMDb page

Please share the URL of the next page as well, i.e. the page where you’re actually seeing the error.

That “Try again later” message indeed means you’ve been temporarily locked out. So please try a few hours later or perhaps even create a second account for testing this.

Thanks a lot!

**Comment by jessestu291** [comment]
Thanks for your reply!

**- Level:** Series
- **Title:** The X-Files
- **-Year** 1993
- **IMDb:** https://www.imdb.com/title/tt0106179/

This is the information that was giving me the error, however now it seems that I am getting the "try again later" message no matter what, even on a different account.

**Comment by ocram** [comment]
That helped a lot, thanks!

Can you please try again? It should work now.

It was not an error message but an existing entry for the same IMDb URL, where the author used a (wrong) title that looked like an error. The IMDb URL, which we use to detect and merge duplicate entries, has now been released so that it can be used again. This will also happen less frequently in the future and will be resolved faster.

**Comment by jessestu291** [comment]
Hey it worked!  Thanks!  

Are we able to edit titles that we add?  I was in a hurry and slightly misspelled it lol.

I may have noticed something else.  It seems that certain edits I make are tagged as commercial content.  I'm pretty sure it was one of the hemophobia tags but can't tell for sure.  

Just another quick inquiry, will we be able to delete edits that we make in the future?  Thanks again!

**Comment by ocram** [comment]
Glad to hear that it worked, thank you!

Metadata like titles, years or IMDb URLs of a movie or TV show indeed cannot be edited yet – although such a basic feature missing is quite embarrassing. Sorry for that!

So when you need some edit right now, please feel free to look up the project’s email address at any time, either from the contact page linked at the bottom or here on GitHub, and send a short request. It will be done as quickly as possible, promise.

As for the annotations that may be classified wrongly, this would definitely be something that would be fixed immediately. Unfortunately, more details would be required to find any such bug. Why do you think that they might have been classified as “commercial content”? Where do you see that?

Is it on the movie or TV show’s details page, i.e. `https://www.moviecontentfilter.com/works/*`, where “commercial content” is listed as a topic? You can click on that topic, which opens `https://www.moviecontentfilter.com/works/*/topics/*`, and you should be able to see which exact position in the work was marked as “commercial content”.

Of course, it can easily happen that one has just picked the wrong category from the drop-down lists. Or scrolling with the mouse wheel has accidentally changed that list to a wrong value afterwards.

So in order to find the bug, if there is any, I’m afraid we’d have to know the exact selection that leads to a wrong category in the output. Sorry!

With regard to deleting an edit, you’re referring to the deletion of a single annotation of any category in a movie or TV show, right? This is absolutely necessary sometimes, sure, but when it comes to designing the user interface, the question was really how to enable this without confusing users or inviting them to delete the wrong annotations.

So in a perfect world, we’d take a screenshot in the middle of any single annotation and store it with that annotation. So you could review the annotations and have a visual overview over what to delete and what to keep. But since I’m fairly certain copyright would cause problems for us there, although some people might see this as “fair use” or “quoting”, we cannot do this.

Thus, when clicking on a topic on the work’s details page, you’re presented with a list of all your annotations – which might get really long if there is a lot of content from that topic. This is bad UX, and we don’t want users to delete the wrong content and keep what should have been deleted. There must be something better.

So what we *do* have right now is the voting mechanism. Did you see it? When clicking through from the work to the topic and finally to a single annotation, you can vote up or down. The idea was that the author themself has much more power in voting and we count their vote as 10× a normal vote, for example. And when a threshold is reached, e.g. 12, or perhaps really just 10, that edit is deleted. What do you think?

**Comment by jessestu291** [comment]
Ok got it!  I'll see if I can replicate that error and let you know.  I appreciate the work you've done!  Looks like you've been working on it recently and that's awesome!

**Comment by ocram** [comment]
Thanks, looking forward to your continued feedback!

**Comment by jessestu291** [comment]
Sorry to bother you again, I was just curious if there is a discord channel for this?  It'd be awesome to have a community together on the project.  Thanks!

**Comment by ocram** [comment]
Not yet, unfortunately. And to be honest, there hasn’t been much of a “community” on here so far.

One reason for that is, of course, that resources have been limited for this project, no significant outreach to communities and users has been made and all the available time, if any, is being used for the technical development.

I don’t know what’s the best form for such a community, whether it’s an IRC channel, Discord channel, Discourse discussion forum, subreddit, messenger group, etc. But I would be grateful if someone else (perhaps even you?) would manage any community we may have.

And, as said before, please feel free to send an email at any time.

**Comment by jessestu291** [comment]
Ok cool I'll keep that in mind!

Is there a way to use the editor offline?  I was wanting to test some things out and didn't want to publish a bunch of inaccurate test filters.  Or maybe a way to make an edit private?

**Comment by ocram** [comment]
As soon as you have *started* the editor, you *can* indeed use it offline. That is, when `https://www.moviecontentfilter.com/works/*/contribute` has loaded completely, you can get on a plane and make hundreds of annotations while up in the air without any internet access. When submitting these annotations, you need internet access again.

But it seems you don’t actually care about connectivity and instead want to avoid submitting or publishing the annotations. So if that’s the case, you can create a new movie or TV show with *any* title, year and IMDb URL, then send an email and we’ll make it *unlisted*, i.e. it’s still available for anyone who has the URL, but it’s not listed or linked in the directory. Would that help?

Apart from that, another plan is to allow anyone to delete their own movie or TV show (that they created on the site) with all annotations within 7 days of creation. What do you think?

Yet another idea would be to allow anybody to choose between “Public” and “Unlisted” when adding a movie or TV show.

**Comment by jessestu291** [comment]
Sounds great!  I'll let you know!
