### ISSUE TITLE
Transpiler issue, process walk-through would be helpful.

### ISSUE THREAD

**Issue by spartahawk** [delight-im/MovieContentFilter#3]
This is excellent work! I hope any negative comments from Ycombinator or wherever didn't discourage you! Don't give up on this thing. Once a community gets going, I think it will really take off! There are millions of people who would love to know an open-source tool like this exists.

I'm having an issue with the transpiler. It refuses to recognize that I have selected several filtering preferences when I go to download the filters. "Nothing found to filter, please adjust your
preferences." Any ideas on how to resolve this?

Also, I think something helpful to get this some support and a community behind it would be a full walk-through for people who may not be able to see the process steps so clearly themselves. Especially how to apply the filters and play the content with them applied (in VLC for example). I am also unsure if the tools provided essentially do what your transpiler does, and how to load that from my end.

Edit: I now see that if none of the selected filters are found in the .mcf file, nothing can be applied, so the above error shows up. That wasn't quite obvious. Perhaps change the wording to "The selected .mcf file contains none of the filters/severity in your preferences."

**Comment by mwaclawek** [comment]
Thank you so much for your interest in this project, your appreciation and your kind words :)

> I'm having an issue with the transpiler. It refuses to recognize that I have selected several filtering preferences when I go to download the filters. "Nothing found to filter, please adjust your preferences." Any ideas on how to resolve this?

That problem occurs whenever the applied selections and the contents of the MCF text file don't match up, i.e. when they don't share any features and there's no intersection.

Since you found the solution to this problem yourself already, could this have been a simple case of bad communication? I *thought* that the current explanation that you quoted was already (a little bit) helpful. But I agree that there may be many better ways to express this. Do you have any ideas?

An alternative that I just thought of is the following: Even if there's not a single filter directive that can be exported (because there were no matches), why not just export an empty result file (that plays the complete movie without interruption)? But in addition to that, we could show a dialog explaining the results along with each download. Example: "The downloaded file is a filter that can be applied to the movie that you own. There have been changes at {n} positions in the movie that were exported as per your selected criteria. Please adjust your criteria in order to change the set of included filters, e.g. to filter less or more scenes."

Sometimes, having the unchanged movie (without any filters) is exactly what you want, because, well, that's what resulted from the filters based on your specified criteria. So it may indeed be better than a warning or error, such as the one you experienced.

> Also, I think something helpful to get this some support and a community behind it would be a full walk-through for people who may not be able to see the process steps so clearly themselves. Especially how to apply the filters and play the content with them applied (in VLC for example).

Improving the tools and putting more emphasis on the correct sequence of steps (perhaps with a guided walk-through) is definitely of top priority. If you can help, you are welcome to support this process with further issues. Is there anything specific that you can point out?

We could certainly turn this single-page transpiler into a multi-page application. But I wanted to keep it simple and I think it's really possible to have a simple user interface without splitting this into more pages.

First thing, what about collapsing the list of selections or criteria by default? It could be expanded as needed. That would make the page much, much shorter.

Apart from that, I think we could make the walk-through clear, even if everything is on a single page, if we added some explanatory text to the single boxes:

 1. Input: Please open your MCF filter file (usually `.mcf`), copy its content and paste it into the following field. You can find such MCF filter files in the "Examples" section of our official repository. If you can't find your movie there, why not try to create your first own filter? We will be happy to help you! (Yes, we could simplify this with a server-side application that offers a list of loadable movies. But you wouldn't be able to host this yourself anymore, without any internet connection, without installing anything other than your browser.)
 1. Synchronization: Having pasted your MCF filter content, the start and end time of the movie should have been added below, as seen by the creators of the filter file. Please check if this matches with your movie. Why is this necessary? Because movies are distributed in multiple versions, some shorter, some longer, and some even differ in speed, e.g. being 1.05x the speed of another version. The filters can only be applied correctly if your version is synchronized with the one from of the creators.
 1. VLC media player: Are you using [VLC media player](https://www.videolan.org/vlc/) to play your videos? (You should!) If you do, please enter the path ("URI") to the movie source on your local computer.

   * `file:///Example.mp4` (or similar) for movies stored on your hard drive
   * `http://example.com/Example.mp4` (or similar) for movies accessible from the web
   * `dvd://e:\@1` (or similar) for movies available on an inserted DVD disc
   * `bluray:///Example` (or similar) for movies available on an inserted Blu-ray disc

 1. Preferences: Please choose your criteria here that will decide which types of content to block and which types to accept. If you have previously set your preferences, they should usually have been saved so that you don't have to enter them again.
 1. Download: As the final step (before watching), you can download your personal MCF patch files here. These patch files are available for the two video players "VLC media player" and "MPlayer". Please store the downloaded file on your hard drive. It's a very small file with a size that is usually in the KB (kilobyte) range, whereas your actual movie content is often in the MB (megabyte) or GB (gigabyte) range. Having downloaded the MCF patch file, just open it with the designated video player software.
 1. Happy watching!

> Once a community gets going, I think it will really take off! There are millions of people who would love to know an open-source tool like this exists.

Thank you! Please feel free to spread the word if you can :) You are invited to contribute otherwise as well, of course, but creating the filters is a manual (and time-consuming) task. The only way to speed this up is to have more volunteers (or a third-party market). But as soon as a filter is there, thousands can benefit instantly.

**Comment by spartahawk** [comment]
I think those instructions and your response thoughts for solutions are perfect.

One thing that would make creating filters easier is to perhaps make a plugin for VLC. When you're viewing the content, you see a panel below or something where the filters are visually displayed (like video-editing software, with captions during certain places etc) and have a button for Start/StopFilter, then check audio and or video, and the filter category. Many could be applied quickly this way. I'm sure it would take some work though.

**Comment by mwaclawek** [comment]
Thanks again!

Can you please check the updated transpiler ("Tools" section)? You can use the link at the top of the repository to see the hosted version.

The captions and labels have been improved, more documentation has been added and your suggestion for the warning message (instead of the "Nothing found to filter") has been incorporated.

Does that solve this issue?

**Comment by spartahawk** [comment]
Everything looks great! Nice job! Thanks.
